version: "3.9"

services:
  db:
    container_name: "${CONTAINER_PREFIX}_db"
    image: mysql:5.7.44
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - .db:/var/lib/mysql
    ports:
      - "3306:3306"

  webserver:
    container_name: "${CONTAINER_PREFIX}_web"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${WEB_EXTERNAL_PORT}:80"
    depends_on:
      - db

  phpmyadmin:
    container_name: "${CONTAINER_PREFIX}_admin"
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "${ADMIN_EXTERNAL_PORT}:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    depends_on:
      - db